/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

public class AddTransactionManagement extends javax.swing.JPanel implements TransactionServiceAware {

    private TransactionService transactionService;
    private final PatientService patientService;
    private final TransactionTypeService transactionTypeService;

    public AddTransactionManagement() {
        this.transactionService = new TransactionServiceImpl();
        this.patientService = new PatientServiceImpl();
        this.transactionTypeService = new TransactionTypeServiceImpl();
        initComponents();
        savetTransaction.setEnabled(false);
        savetTransaction.setVisible(false);
        patientLabel.setVisible(false);
        patientName.setVisible(false);
        typeContainer.setVisible(false);
        typeLabel.setVisible(false);
        currentCost.setVisible(false);
        currentCostLabel.setVisible(false);
    }

    @Override
    public void setTransactionService(TransactionService transactionService) {
        this.transactionService = transactionService;
    }

    @Override
    public List<Transaction> getAllTransactions() {
        return transactionService.getAllTransactions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        wrapper = new javax.swing.JPanel();
        savetTransaction = new test.CustomButton();
        submitBtn = new test.CustomButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        costTxt = new javax.swing.JTextField();
        typeID = new javax.swing.JTextField();
        patientID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        patientID3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        paymentStstus = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        dateTxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        patientName = new javax.swing.JLabel();
        patientLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        typeContainer = new javax.swing.JLabel();
        currentCost = new javax.swing.JLabel();
        currentCostLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 119, 204));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create New Transaction");

        wrapper.setOpaque(false);

        savetTransaction.setBackground(new java.awt.Color(0, 51, 0));
        savetTransaction.setBorder(null);
        savetTransaction.setForeground(new java.awt.Color(255, 255, 255));
        savetTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/updateBtn.png"))); // NOI18N
        savetTransaction.setText("Save Transaction");
        savetTransaction.setBorderColor(new java.awt.Color(0, 51, 0));
        savetTransaction.setColor(new java.awt.Color(0, 51, 0));
        savetTransaction.setColorClick(new java.awt.Color(0, 51, 0));
        savetTransaction.setColorOver(new java.awt.Color(0, 102, 0));
        savetTransaction.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        savetTransaction.setRadius(8);
        savetTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savetTransactionActionPerformed(evt);
            }
        });

        submitBtn.setBackground(new java.awt.Color(0, 51, 0));
        submitBtn.setBorder(null);
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("Submit");
        submitBtn.setBorderColor(new java.awt.Color(0, 51, 0));
        submitBtn.setColor(new java.awt.Color(0, 51, 0));
        submitBtn.setColorClick(new java.awt.Color(0, 51, 0));
        submitBtn.setColorOver(new java.awt.Color(0, 102, 0));
        submitBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        submitBtn.setRadius(8);
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Cost:");

        jLabel4.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Transaction Type ID:");

        costTxt.setBackground(new java.awt.Color(0, 119, 204));
        costTxt.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        costTxt.setForeground(new java.awt.Color(255, 255, 255));
        costTxt.setBorder(null);

        typeID.setBackground(new java.awt.Color(0, 119, 204));
        typeID.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        typeID.setForeground(new java.awt.Color(255, 255, 255));
        typeID.setBorder(null);

        patientID.setBackground(new java.awt.Color(0, 119, 204));
        patientID.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        patientID.setForeground(new java.awt.Color(255, 255, 255));
        patientID.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Patient ID:");

        patientID3.setBackground(new java.awt.Color(0, 119, 204));
        patientID3.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        patientID3.setForeground(new java.awt.Color(255, 255, 255));
        patientID3.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Remarks:");

        paymentStstus.setBackground(new java.awt.Color(0, 119, 204));
        paymentStstus.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        paymentStstus.setForeground(new java.awt.Color(204, 204, 204));
        paymentStstus.setText("e.g Paid, Cancelled, Pending . . .");
        paymentStstus.setBorder(null);
        paymentStstus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paymentStstusFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                paymentStstusFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Payment Status :");

        dateLabel.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setText("Date:");

        dateTxt.setBackground(new java.awt.Color(0, 119, 204));
        dateTxt.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        dateTxt.setForeground(new java.awt.Color(255, 255, 255));
        dateTxt.setBorder(null);

        jPanel1.setOpaque(false);

        patientName.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        patientName.setForeground(new java.awt.Color(255, 255, 255));
        patientName.setText(" Name Container");

        patientLabel.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        patientLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientLabel.setText("Patient:");

        typeLabel.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(255, 255, 255));
        typeLabel.setText("Type:");

        typeContainer.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        typeContainer.setForeground(new java.awt.Color(255, 255, 255));
        typeContainer.setText("Type  Container");

        currentCost.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        currentCost.setForeground(new java.awt.Color(255, 255, 255));
        currentCost.setText(" Cost Container");

        currentCostLabel.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        currentCostLabel.setForeground(new java.awt.Color(255, 255, 255));
        currentCostLabel.setText("Current Cost:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(typeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(patientLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(currentCostLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentCost, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientLabel)
                    .addComponent(patientName))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(typeContainer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentCostLabel)
                    .addComponent(currentCost))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout wrapperLayout = new javax.swing.GroupLayout(wrapper);
        wrapper.setLayout(wrapperLayout);
        wrapperLayout.setHorizontalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wrapperLayout.createSequentialGroup()
                        .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(savetTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(wrapperLayout.createSequentialGroup()
                                .addComponent(dateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136))
                            .addGroup(wrapperLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paymentStstus, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(wrapperLayout.createSequentialGroup()
                            .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, wrapperLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(patientID3))
                                    .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(wrapperLayout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(costTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(wrapperLayout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(typeID, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(wrapperLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(patientID, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, 0)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        wrapperLayout.setVerticalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapperLayout.createSequentialGroup()
                        .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(patientID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(typeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(costTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(patientID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(paymentStstus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savetTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(139, 139, 139))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wrapper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wrapper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        try {
            int patientIDValue = Integer.parseInt(patientID.getText().trim());
            int typeIDValue = Integer.parseInt(typeID.getText().trim());

            Patient patient = patientService.getPatient(patientIDValue);
            TransactionType type = transactionTypeService.getTransactionType(typeIDValue);

            if (patient == null) {
                JOptionPane.showMessageDialog(this, "No patient found with ID: " + patientIDValue, "Invalid Patient ID", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (type == null) {
                JOptionPane.showMessageDialog(this, "No transaction type found with ID: " + typeIDValue, "Invalid Type ID", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Update UI labels with fetched data
            patientName.setText(patient.getLastName() + ", " + patient.getFirstName());
            typeContainer.setText(type.getTypeName());
            currentCost.setText(String.valueOf(type.getDefaultCost()));

            // Show review dialog
            String reviewMessage = "Patient: " + patient.getLastName() + ", " + patient.getFirstName()
                    + "\nTransaction Type: " + type.getTypeName()
                    + "\nDefault Cost: " + type.getDefaultCost()
                    + "\n\nAre these details correct?";
            int confirm = JOptionPane.showConfirmDialog(this, reviewMessage, "Review Transaction Details", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                savetTransaction.setEnabled(true);
                patientLabel.setVisible(true);
                patientName.setVisible(true);
                typeLabel.setVisible(true);
                typeContainer.setVisible(true);
                currentCostLabel.setVisible(true);
                currentCost.setVisible(true);
                savetTransaction.setVisible(true);
            } else {
                savetTransaction.setEnabled(false);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric IDs for Patient and Transaction Type.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error reviewing details: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void savetTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savetTransactionActionPerformed
        // TODO add your handling code here:
        try {
            int patientIDValue = Integer.parseInt(patientID.getText().trim());
            int typeIDValue = Integer.parseInt(typeID.getText().trim());
            String dateStr = dateTxt.getText().trim();
            String remarks = patientID3.getText().trim();
            double totalCost = Double.parseDouble(costTxt.getText().trim());
            String status = paymentStstus.getText().trim();

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date transactionDate = sdf.parse(dateStr);

            Patient patient = patientService.getPatient(patientIDValue);
            TransactionType type = transactionTypeService.getTransactionType(typeIDValue);

            if (patient == null || type == null) {
                JOptionPane.showMessageDialog(this, "Invalid Patient ID or Transaction Type ID.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Transaction transaction = new Transaction();
            transaction.setPatient(patient);
            transaction.setTransactionType(type);
            transaction.setTransactionDate(transactionDate);
            transaction.setRemarks(remarks);
            transaction.setTotalCost(totalCost);
            transaction.setStatus(status);

            int result = transactionService.saveTransaction(transaction);
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Transaction saved successfully with ID: " + transaction.getTransactionID(), "Success", JOptionPane.INFORMATION_MESSAGE);
                // Clear fields after saving
                patientID.setText("");
                typeID.setText("");
                dateTxt.setText("");
                patientID3.setText("");
                costTxt.setText("");
                paymentStstus.setText("");
                patientName.setText("Name Container");
                typeContainer.setText("Type Container");
                currentCost.setText("Cost Container");
                savetTransaction.setEnabled(false);
                patientLabel.setVisible(false);
                patientName.setVisible(false);
                typeLabel.setVisible(false);
                typeContainer.setVisible(false);
                currentCostLabel.setVisible(false);
                currentCost.setVisible(false);
                savetTransaction.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to save transaction.", "Save Failed", JOptionPane.WARNING_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric values for IDs and Total Cost.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Please enter the date in yyyy-MM-dd format.", "Date Format Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saving transaction: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_savetTransactionActionPerformed

    private void paymentStstusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentStstusFocusGained
        // TODO add your handling code here:
        if (paymentStstus.getText().equals("e.g Paid, Cancelled, Pending . . .")) {
            paymentStstus.setText("");
        }
    }//GEN-LAST:event_paymentStstusFocusGained

    private void paymentStstusFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentStstusFocusLost
        // TODO add your handling code here:
        if (paymentStstus.getText().trim().isEmpty()) {
            paymentStstus.setText("e.g Paid, Cancelled, Pending . . .");
        }
    }//GEN-LAST:event_paymentStstusFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField costTxt;
    private javax.swing.JLabel currentCost;
    private javax.swing.JLabel currentCostLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField patientID;
    private javax.swing.JTextField patientID3;
    private javax.swing.JLabel patientLabel;
    private javax.swing.JLabel patientName;
    private javax.swing.JTextField paymentStstus;
    private test.CustomButton savetTransaction;
    private test.CustomButton submitBtn;
    private javax.swing.JLabel typeContainer;
    private javax.swing.JTextField typeID;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JPanel wrapper;
    // End of variables declaration//GEN-END:variables
}
