/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test;

import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.List;

/**
 *
 * @author Admin
 */
public class DeleteTransactionManagement extends javax.swing.JPanel implements TransactionServiceAware {

    private TransactionService transactionService;
    private TransactionManagement transactionManagement; // Reference to update mngmntTbl
    private int currentTransactionID; // Store the ID of the transaction being displayed

    /**
     * Creates new form DeleteTransactionManagement
     */
    public DeleteTransactionManagement() {
        this.transactionService = new TransactionServiceImpl();
        initComponents();
        deleteInfoPanel.setVisible(false);
    }

    public DeleteTransactionManagement(TransactionService transactionService, TransactionManagement transactionManagement) {
        this.transactionService = transactionService;
        this.transactionManagement = transactionManagement;
        initComponents();
        deleteInfoPanel.setVisible(false);
    }

    @Override
    public void setTransactionService(TransactionService transactionService) {
        this.transactionService = transactionService;
    }

    @Override
    public List<Transaction> getAllTransactions() {
        return transactionService.getAllTransactions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idToFind = new javax.swing.JTextField();
        searchBtn = new test.CustomButton();
        deleteInfoPanel = new javax.swing.JPanel();
        iD = new javax.swing.JLabel();
        row4 = new javax.swing.JLabel();
        row1 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        patientName = new javax.swing.JLabel();
        row2 = new javax.swing.JLabel();
        row3 = new javax.swing.JLabel();
        transType = new javax.swing.JLabel();
        row6 = new javax.swing.JLabel();
        row5 = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        deleteBtn = new test.CustomButton();

        setBackground(new java.awt.Color(0, 119, 204));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Delete Transaction");

        jLabel2.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Transaction ID :");

        idToFind.setBackground(new java.awt.Color(0, 119, 204));
        idToFind.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        idToFind.setForeground(new java.awt.Color(255, 255, 255));
        idToFind.setBorder(null);

        searchBtn.setBackground(new java.awt.Color(0, 51, 0));
        searchBtn.setBorder(null);
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/searchBtn.png"))); // NOI18N
        searchBtn.setText("Search ID");
        searchBtn.setColor(new java.awt.Color(0, 51, 0));
        searchBtn.setColorClick(new java.awt.Color(0, 51, 0));
        searchBtn.setColorOver(new java.awt.Color(0, 102, 0));
        searchBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        searchBtn.setRadius(8);
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });

        deleteInfoPanel.setOpaque(false);

        iD.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        iD.setForeground(new java.awt.Color(255, 255, 255));
        iD.setText("Patient ID:");

        row4.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        row4.setForeground(new java.awt.Color(255, 255, 255));
        row4.setText(" ID:");

        row1.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        row1.setForeground(new java.awt.Color(255, 255, 255));
        row1.setText("Date:");

        date.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("Date Recorded");

        patientName.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        patientName.setForeground(new java.awt.Color(255, 255, 255));
        patientName.setText("Patient name");

        row2.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        row2.setForeground(new java.awt.Color(255, 255, 255));
        row2.setText("Patient:");

        row3.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        row3.setForeground(new java.awt.Color(255, 255, 255));
        row3.setText("Type:");

        transType.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        transType.setForeground(new java.awt.Color(255, 255, 255));
        transType.setText("Transaction Type");

        row6.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        row6.setForeground(new java.awt.Color(255, 255, 255));
        row6.setText("Stutus:");

        row5.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        row5.setForeground(new java.awt.Color(255, 255, 255));
        row5.setText("Cost:");

        cost.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        cost.setForeground(new java.awt.Color(255, 255, 255));
        cost.setText("Total cost");

        status.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setText("Transaction status");

        deleteBtn.setBackground(new java.awt.Color(0, 51, 0));
        deleteBtn.setBorder(null);
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deleteBtn.png"))); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.setColor(new java.awt.Color(0, 51, 0));
        deleteBtn.setColorClick(new java.awt.Color(0, 51, 0));
        deleteBtn.setColorOver(new java.awt.Color(0, 102, 0));
        deleteBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        deleteBtn.setRadius(8);
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout deleteInfoPanelLayout = new javax.swing.GroupLayout(deleteInfoPanel);
        deleteInfoPanel.setLayout(deleteInfoPanelLayout);
        deleteInfoPanelLayout.setHorizontalGroup(
            deleteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteInfoPanelLayout.createSequentialGroup()
                        .addGroup(deleteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(deleteInfoPanelLayout.createSequentialGroup()
                                .addComponent(row4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(deleteInfoPanelLayout.createSequentialGroup()
                                .addComponent(row1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                        .addGap(12, 12, 12)
                        .addGroup(deleteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(deleteInfoPanelLayout.createSequentialGroup()
                                .addComponent(row5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cost))
                            .addGroup(deleteInfoPanelLayout.createSequentialGroup()
                                .addComponent(row6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(status)))
                        .addGap(85, 85, 85))
                    .addGroup(deleteInfoPanelLayout.createSequentialGroup()
                        .addComponent(row2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(deleteInfoPanelLayout.createSequentialGroup()
                        .addComponent(row3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transType, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        deleteInfoPanelLayout.setVerticalGroup(
            deleteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteInfoPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(deleteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteInfoPanelLayout.createSequentialGroup()
                        .addGroup(deleteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(row4)
                            .addComponent(iD))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(deleteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(row1)
                            .addComponent(date)))
                    .addGroup(deleteInfoPanelLayout.createSequentialGroup()
                        .addGroup(deleteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(row5)
                            .addComponent(cost))
                        .addGap(0, 0, 0)
                        .addGroup(deleteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(row6)
                            .addComponent(status))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(deleteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteInfoPanelLayout.createSequentialGroup()
                        .addGroup(deleteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(row2)
                            .addComponent(patientName))
                        .addGap(0, 0, 0)
                        .addGroup(deleteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(row3)
                            .addComponent(transType))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteInfoPanelLayout.createSequentialGroup()
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idToFind, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addComponent(deleteInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idToFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        // TODO add your handling code here:
        String idText = idToFind.getText().trim();

        if (!idText.isEmpty()) {
            try {
                int transactionID = Integer.parseInt(idText);
                Transaction transaction = transactionService.getTransaction(transactionID);
                if (transaction != null) {
                    // Update deleteInfoPanel with transaction details
                    iD.setText(String.valueOf(transaction.getTransactionID()));
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    date.setText(sdf.format(transaction.getTransactionDate()));
                    patientName.setText(transaction.getPatient() != null
                            ? transaction.getPatient().getLastName() + ", " + transaction.getPatient().getFirstName()
                            : "N/A");
                    transType.setText(transaction.getTransactionType() != null
                            ? transaction.getTransactionType().getTypeName()
                            : "N/A");
                    cost.setText(String.valueOf(transaction.getTotalCost()));
                    status.setText(transaction.getStatus());
                    currentTransactionID = transaction.getTransactionID(); // Store ID for deletion
                    deleteInfoPanel.setVisible(true); // Show details and delete button
                    // Update mngmntTbl in TransactionManagement
                    transactionManagement.loadSingleTransaction(transaction);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "No transaction found for Transaction ID: " + idText,
                            "Not Found",
                            JOptionPane.WARNING_MESSAGE);
                    deleteInfoPanel.setVisible(false); // Hide panel if no transaction found
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "Invalid Transaction ID format. Please enter a valid number.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                deleteInfoPanel.setVisible(false); // Hide panel on invalid input
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Please enter a Transaction ID.",
                    "Input Required",
                    JOptionPane.WARNING_MESSAGE);
            deleteInfoPanel.setVisible(false); // Hide panel if input is empty
        }
    }//GEN-LAST:event_searchBtnMouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        // TODO add your handling code here:
         int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete Transaction ID: " + currentTransactionID + "?\nThis action cannot be undone.",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            int result = transactionService.deleteTransaction(currentTransactionID);
            if (result > 0) {
                JOptionPane.showMessageDialog(this,
                        "Transaction ID: " + currentTransactionID + " deleted successfully.",
                        "Deletion Successful",
                        JOptionPane.INFORMATION_MESSAGE);
                deleteInfoPanel.setVisible(false); // Hide panel after deletion
                idToFind.setText(""); // Clear input field
                transactionManagement.clearTable(); // Clear the table in TransactionManagement
            } else {
                JOptionPane.showMessageDialog(this,
                        "Failed to delete Transaction ID: " + currentTransactionID + ".",
                        "Deletion Failed",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cost;
    private javax.swing.JLabel date;
    private test.CustomButton deleteBtn;
    private javax.swing.JPanel deleteInfoPanel;
    private javax.swing.JLabel iD;
    private javax.swing.JTextField idToFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel patientName;
    private javax.swing.JLabel row1;
    private javax.swing.JLabel row2;
    private javax.swing.JLabel row3;
    private javax.swing.JLabel row4;
    private javax.swing.JLabel row5;
    private javax.swing.JLabel row6;
    private test.CustomButton searchBtn;
    private javax.swing.JLabel status;
    private javax.swing.JLabel transType;
    // End of variables declaration//GEN-END:variables
}
