/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class DeleteTransactionType extends javax.swing.JPanel implements TransactionTypeServiceAware {

    private TransactionTypeService transactionTypeService;

    /**
     * Creates new form DeleteTransactionType
     */
    public DeleteTransactionType() {
        initComponents();
        deleteResultModal.setVisible(false);
        deleteBtn.setVisible(false);
    }

    @Override
    public void setTransactionTypeService(TransactionTypeService transactionTypeService) {
        this.transactionTypeService = transactionTypeService;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        deleteIDTxt = new javax.swing.JTextField();
        deleteBtn = new test.CustomButton();
        deleteResultModal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ttDeleteResult = new javax.swing.JLabel();
        descDeleteResult = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dcDeleteResult = new javax.swing.JLabel();
        findTransactionBtn = new test.CustomButton();

        setBackground(new java.awt.Color(0, 119, 204));
        setMaximumSize(new java.awt.Dimension(452, 180));
        setMinimumSize(new java.awt.Dimension(452, 180));
        setPreferredSize(new java.awt.Dimension(452, 180));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Delete Transaction Type");

        jLabel2.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Transaction Type ID:");

        deleteIDTxt.setBackground(new java.awt.Color(0, 119, 204));
        deleteIDTxt.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        deleteIDTxt.setForeground(new java.awt.Color(255, 255, 255));
        deleteIDTxt.setBorder(null);

        deleteBtn.setBackground(new java.awt.Color(0, 51, 0));
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deleteBtn.png"))); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.setBorderColor(new java.awt.Color(0, 51, 0));
        deleteBtn.setColor(new java.awt.Color(0, 51, 0));
        deleteBtn.setColorClick(new java.awt.Color(6, 30, 1));
        deleteBtn.setColorOver(new java.awt.Color(0, 153, 0));
        deleteBtn.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        deleteBtn.setRadius(10);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        deleteResultModal.setBackground(new java.awt.Color(0, 119, 204));

        jLabel3.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Transaction Type:");

        jLabel4.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Description:");

        ttDeleteResult.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        ttDeleteResult.setForeground(new java.awt.Color(255, 255, 255));
        ttDeleteResult.setText("None");

        descDeleteResult.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        descDeleteResult.setForeground(new java.awt.Color(255, 255, 255));
        descDeleteResult.setText("None");

        jLabel7.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Default Cost:");

        dcDeleteResult.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        dcDeleteResult.setForeground(new java.awt.Color(255, 255, 255));
        dcDeleteResult.setText("None");

        javax.swing.GroupLayout deleteResultModalLayout = new javax.swing.GroupLayout(deleteResultModal);
        deleteResultModal.setLayout(deleteResultModalLayout);
        deleteResultModalLayout.setHorizontalGroup(
            deleteResultModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteResultModalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteResultModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteResultModalLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ttDeleteResult))
                    .addGroup(deleteResultModalLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descDeleteResult))
                    .addGroup(deleteResultModalLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcDeleteResult)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deleteResultModalLayout.setVerticalGroup(
            deleteResultModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteResultModalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteResultModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ttDeleteResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deleteResultModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(descDeleteResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deleteResultModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dcDeleteResult))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        findTransactionBtn.setBackground(new java.awt.Color(0, 51, 0));
        findTransactionBtn.setBorder(null);
        findTransactionBtn.setForeground(new java.awt.Color(255, 255, 255));
        findTransactionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/searchBtn.png"))); // NOI18N
        findTransactionBtn.setText("Find Transaction");
        findTransactionBtn.setBorderColor(new java.awt.Color(0, 51, 0));
        findTransactionBtn.setColor(new java.awt.Color(0, 51, 0));
        findTransactionBtn.setColorClick(new java.awt.Color(6, 30, 1));
        findTransactionBtn.setColorOver(new java.awt.Color(0, 153, 0));
        findTransactionBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        findTransactionBtn.setRadius(10);
        findTransactionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findTransactionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteResultModal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteIDTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(findTransactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(deleteIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findTransactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(deleteResultModal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
      try {
            // Get transaction type ID from text field
            String typeIdText = deleteIDTxt.getText().trim();
            if (typeIdText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a Transaction Type ID.", "Input Error", JOptionPane.ERROR_MESSAGE);
                deleteResultModal.setVisible(false);
                return;
            }

            int typeId;
            try {
                typeId = Integer.parseInt(typeIdText);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid Transaction Type ID format. Please enter a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
                deleteResultModal.setVisible(false);
                return;
            }

            // Check if service is available
            if (transactionTypeService == null) {
                JOptionPane.showMessageDialog(this, "Transaction service is not available.", "Service Error", JOptionPane.ERROR_MESSAGE);
                deleteResultModal.setVisible(false);
                return;
            }

            // Show confirmation dialog
            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Are you sure you want to delete transaction type with ID " + typeId + "?\nThis action cannot be undone.",
                    "Confirm Deletion",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            // Proceed only if the user selects "Yes"
            if (confirm != JOptionPane.YES_OPTION) {
                return; // User canceled, keep modal visible
            }

            // Proceed with deletion
            int rowsAffected = transactionTypeService.deleteTransactionType(typeId);
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Transaction type with ID " + typeId + " deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                // Refresh the parent table
                if (getParent() instanceof TransactionTypePage) {
                    ((TransactionTypePage) getParent()).viewAllTransactionType();
                }
                // Play success sound
                MouseClick.playNotificationSound();
                // Clear input and hide modal
                deleteIDTxt.setText("");
                ttDeleteResult.setText("None");
                descDeleteResult.setText("None");
                dcDeleteResult.setText("None");
                deleteResultModal.setVisible(false);
                deleteBtn.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Cannot delete this transaction type because it is being used by existing transactions or does not exist.", "Cannot Delete", JOptionPane.WARNING_MESSAGE);
                deleteResultModal.setVisible(false);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error processing deletion: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            deleteResultModal.setVisible(false);
            deleteIDTxt.setText("");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void findTransactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findTransactionBtnActionPerformed
        // TODO add your handling code here:
       try {
            // Get transaction type ID from text field
            String typeIdText = deleteIDTxt.getText().trim();
            if (typeIdText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a Transaction Type ID.", "Input Error", JOptionPane.ERROR_MESSAGE);
                deleteResultModal.setVisible(false);
                return;
            }

            int typeId;
            try {
                typeId = Integer.parseInt(typeIdText);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid Transaction Type ID format. Please enter a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
                deleteResultModal.setVisible(false);
                return;
            }

            // Check if service is available
            if (transactionTypeService == null) {
                JOptionPane.showMessageDialog(this, "Transaction service is not available.", "Service Error", JOptionPane.ERROR_MESSAGE);
                deleteResultModal.setVisible(false);
                return;
            }

            // Fetch transaction type
            TransactionType type = transactionTypeService.getTransactionType(typeId);

            if (type == null) {
                JOptionPane.showMessageDialog(this, "No transaction type found with ID: " + typeId, "Not Found", JOptionPane.ERROR_MESSAGE);
                // Clear the display labels and hide the modal
                ttDeleteResult.setText("None");
                descDeleteResult.setText("None");
                dcDeleteResult.setText("None");
                deleteResultModal.setVisible(false);
                return;
            }

            // Update UI with transaction type details and show the modal
            ttDeleteResult.setText(type.getTypeName() != null ? type.getTypeName() : "N/A");
            descDeleteResult.setText(type.getDescription() != null ? type.getDescription() : "N/A");
            dcDeleteResult.setText(type.getDefaultCost() != 0 ? String.format("%.2f", type.getDefaultCost()) : "N/A");
            deleteResultModal.setVisible(true);
            deleteBtn.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error retrieving transaction type: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            deleteResultModal.setVisible(false);
            deleteBtn.setVisible(false);
        }
    }//GEN-LAST:event_findTransactionBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dcDeleteResult;
    private test.CustomButton deleteBtn;
    private javax.swing.JTextField deleteIDTxt;
    private javax.swing.JPanel deleteResultModal;
    private javax.swing.JLabel descDeleteResult;
    private test.CustomButton findTransactionBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel ttDeleteResult;
    // End of variables declaration//GEN-END:variables
}
