/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author Admin
 */
public class FindTransactionManagementPatient extends javax.swing.JPanel implements TransactionServiceAware {

    private TransactionService transactionService;
    private TransactionManagement transactionManagement; // Reference to update mngmntTbl

    /**
     * Creates new form FindTransactionManagementPatient
     */
    public FindTransactionManagementPatient() {
        this.transactionService = new TransactionServiceImpl();
        initComponents();
    }

    public FindTransactionManagementPatient(TransactionService transactionService, TransactionManagement transactionManagement) {
        this.transactionService = transactionService;
        this.transactionManagement = transactionManagement;
        initComponents();
    }

    @Override
    public void setTransactionService(TransactionService transactionService) {
        this.transactionService = transactionService;
    }

    @Override
    public List<Transaction> getAllTransactions() {
        return transactionService.getAllTransactions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        patientdID = new javax.swing.JTextField();
        patientsTR = new test.CustomButton();

        setBackground(new java.awt.Color(0, 119, 204));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Transaction Records");

        jLabel2.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Patient ID:");

        patientdID.setBackground(new java.awt.Color(0, 119, 204));
        patientdID.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        patientdID.setForeground(new java.awt.Color(255, 255, 255));
        patientdID.setBorder(null);

        patientsTR.setBackground(new java.awt.Color(0, 51, 0));
        patientsTR.setBorder(null);
        patientsTR.setForeground(new java.awt.Color(255, 255, 255));
        patientsTR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/searchBtn.png"))); // NOI18N
        patientsTR.setText("Search Records");
        patientsTR.setBorderColor(new java.awt.Color(0, 51, 0));
        patientsTR.setColor(new java.awt.Color(0, 51, 0));
        patientsTR.setColorClick(new java.awt.Color(0, 51, 0));
        patientsTR.setColorOver(new java.awt.Color(0, 102, 0));
        patientsTR.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        patientsTR.setRadius(8);
        patientsTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientsTRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientdID, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(patientsTR, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(patientdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientsTR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void patientsTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientsTRActionPerformed
        // TODO add your handling code here:
        String patientIdText = patientdID.getText().trim();

        if (!patientIdText.isEmpty()) {
            try {
                int patientId = Integer.parseInt(patientIdText);
                List<Transaction> transactions = transactionService.getTransactionsByPatient(patientId);
                if (!transactions.isEmpty()) {
                    // Update mngmntTbl in TransactionManagement
                    DefaultTableModel model = (DefaultTableModel) transactionManagement.getMngmntTbl().getModel();
                    model.setRowCount(0); // Clear existing rows
                    for (Transaction t : transactions) {
                        Object[] row = {
                            t.getTransactionID(),
                            t.getTransactionDate(),
                            t.getPatient() != null ? t.getPatient().getLastName() + ", " + t.getPatient().getFirstName() : "N/A",
                            t.getTransactionType() != null ? t.getTransactionType().getTypeName() : "N/A",
                            t.getTotalCost(),
                            t.getStatus()
                        };
                        model.addRow(row);
                    }
                    // Success message after loading data
                    JOptionPane.showMessageDialog(this,
                            "Patient found. Transactions have been loaded into the table.",
                            "Successfully Found Patient Transactions",
                            JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "No transactions found for Patient ID: " + patientId,
                            "Not Found",
                            JOptionPane.WARNING_MESSAGE);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "Invalid Patient ID format.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Please enter a Patient ID.",
                    "Input Required",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_patientsTRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField patientdID;
    private test.CustomButton patientsTR;
    // End of variables declaration//GEN-END:variables
}
