/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test;

import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.List;

/**
 *
 * @author Admin
 */
public class FindTransactionManagementID extends javax.swing.JPanel implements TransactionServiceAware {

    private TransactionService transactionService;

    /**
     * Creates new form FindTransactionManagementID
     */
    public FindTransactionManagementID() {
        this.transactionService = new TransactionServiceImpl(); // Default service
        initComponents();
        patientRecords.setVisible(false);
    }

    public FindTransactionManagementID(TransactionService transactionService) {
        this.transactionService = transactionService;
        initComponents();
        patientRecords.setVisible(false);
    }

    @Override
    public void setTransactionService(TransactionService transactionService) {
        this.transactionService = transactionService;
    }

    @Override
    public List<Transaction> getAllTransactions() {
        return transactionService.getAllTransactions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        change = new test.CustomButton();
        patientRecords = new javax.swing.JPanel();
        row = new javax.swing.JLabel();
        id1 = new javax.swing.JLabel();
        row1 = new javax.swing.JLabel();
        id2 = new javax.swing.JLabel();
        row2 = new javax.swing.JLabel();
        row3 = new javax.swing.JLabel();
        id3 = new javax.swing.JLabel();
        id4 = new javax.swing.JLabel();
        row4 = new javax.swing.JLabel();
        id5 = new javax.swing.JLabel();
        row5 = new javax.swing.JLabel();
        row6 = new javax.swing.JLabel();
        id6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 119, 204));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Patients Transaction Management");

        jLabel2.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Transaction ID:");

        jTextField1.setBackground(new java.awt.Color(0, 119, 204));
        jTextField1.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jTextField1.setOpaque(true);

        change.setBackground(new java.awt.Color(0, 51, 0));
        change.setBorder(null);
        change.setForeground(new java.awt.Color(255, 255, 255));
        change.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/searchBtn.png"))); // NOI18N
        change.setText("Search Transaction");
        change.setBorderColor(new java.awt.Color(0, 51, 0));
        change.setColor(new java.awt.Color(0, 51, 0));
        change.setColorClick(new java.awt.Color(0, 51, 0));
        change.setColorOver(new java.awt.Color(0, 102, 0));
        change.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        change.setRadius(8);
        change.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeMouseClicked(evt);
            }
        });

        patientRecords.setOpaque(false);

        row.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        row.setForeground(new java.awt.Color(255, 255, 255));
        row.setText("RECOVERED TRANSACTION:");

        id1.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        id1.setForeground(new java.awt.Color(255, 255, 255));
        id1.setText("Date Recorded");

        row1.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        row1.setForeground(new java.awt.Color(255, 255, 255));
        row1.setText("Date:");

        id2.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        id2.setForeground(new java.awt.Color(255, 255, 255));
        id2.setText("Patient name");

        row2.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        row2.setForeground(new java.awt.Color(255, 255, 255));
        row2.setText("Patient:");

        row3.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        row3.setForeground(new java.awt.Color(255, 255, 255));
        row3.setText("Type:");

        id3.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        id3.setForeground(new java.awt.Color(255, 255, 255));
        id3.setText("Transaction Type");

        id4.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        id4.setForeground(new java.awt.Color(255, 255, 255));
        id4.setText("Patient ID:");

        row4.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        row4.setForeground(new java.awt.Color(255, 255, 255));
        row4.setText(" ID:");

        id5.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        id5.setForeground(new java.awt.Color(255, 255, 255));
        id5.setText("Total cost");

        row5.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        row5.setForeground(new java.awt.Color(255, 255, 255));
        row5.setText("Cost:");

        row6.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        row6.setForeground(new java.awt.Color(255, 255, 255));
        row6.setText("Stutus:");

        id6.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        id6.setForeground(new java.awt.Color(255, 255, 255));
        id6.setText("Transaction status");

        javax.swing.GroupLayout patientRecordsLayout = new javax.swing.GroupLayout(patientRecords);
        patientRecords.setLayout(patientRecordsLayout);
        patientRecordsLayout.setHorizontalGroup(
            patientRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientRecordsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientRecordsLayout.createSequentialGroup()
                        .addGroup(patientRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(patientRecordsLayout.createSequentialGroup()
                                .addComponent(row2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id2))
                            .addGroup(patientRecordsLayout.createSequentialGroup()
                                .addComponent(row3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id3))
                            .addComponent(row))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(patientRecordsLayout.createSequentialGroup()
                        .addGroup(patientRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(patientRecordsLayout.createSequentialGroup()
                                .addComponent(row4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id4))
                            .addGroup(patientRecordsLayout.createSequentialGroup()
                                .addComponent(row1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(12, 12, 12)
                        .addGroup(patientRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(patientRecordsLayout.createSequentialGroup()
                                .addComponent(row5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id5))
                            .addGroup(patientRecordsLayout.createSequentialGroup()
                                .addComponent(row6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id6)))
                        .addGap(85, 85, 85))))
        );
        patientRecordsLayout.setVerticalGroup(
            patientRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientRecordsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(row)
                .addGap(0, 0, 0)
                .addGroup(patientRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientRecordsLayout.createSequentialGroup()
                        .addGroup(patientRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(row4)
                            .addComponent(id4))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(patientRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(row1)
                            .addComponent(id1)))
                    .addGroup(patientRecordsLayout.createSequentialGroup()
                        .addGroup(patientRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(row5)
                            .addComponent(id5))
                        .addGap(0, 0, 0)
                        .addGroup(patientRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(row6)
                            .addComponent(id6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 0, 0)
                .addGroup(patientRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(row2)
                    .addComponent(id2))
                .addGap(0, 0, 0)
                .addGroup(patientRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(row3)
                    .addComponent(id3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(patientRecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(change, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientRecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void changeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeMouseClicked
        // TODO add your handling code here:
String transactionIdText = jTextField1.getText().trim();

        if (!transactionIdText.isEmpty()) {
            try {
                int transactionId = Integer.parseInt(transactionIdText);
                Transaction transaction = transactionService.getTransaction(transactionId);
                if (transaction != null) {
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    id1.setText(sdf.format(transaction.getTransactionDate()));
                    id2.setText(transaction.getPatient().getLastName() + ", " + transaction.getPatient().getFirstName());
                    id3.setText(transaction.getTransactionType().getTypeName());
                    id4.setText(String.valueOf(transaction.getPatient().getPatientID()));
                    id5.setText(String.format("%.2f", transaction.getTotalCost()));
                    id6.setText(transaction.getStatus());
                    patientRecords.setVisible(true);
                    // showTransactionDialog(transaction); // Uncomment to use modal dialog
                } else {
                    JOptionPane.showMessageDialog(this, "No transaction found with ID: " + transactionId, "Not Found", JOptionPane.WARNING_MESSAGE);
                    patientRecords.setVisible(false);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid Transaction ID format.", "Error", JOptionPane.ERROR_MESSAGE);
                patientRecords.setVisible(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter a Transaction ID.", "Input Required", JOptionPane.WARNING_MESSAGE);
            patientRecords.setVisible(false);
        }
    }//GEN-LAST:event_changeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private test.CustomButton change;
    private javax.swing.JLabel id1;
    private javax.swing.JLabel id2;
    private javax.swing.JLabel id3;
    private javax.swing.JLabel id4;
    private javax.swing.JLabel id5;
    private javax.swing.JLabel id6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel patientRecords;
    private javax.swing.JLabel row;
    private javax.swing.JLabel row1;
    private javax.swing.JLabel row2;
    private javax.swing.JLabel row3;
    private javax.swing.JLabel row4;
    private javax.swing.JLabel row5;
    private javax.swing.JLabel row6;
    // End of variables declaration//GEN-END:variables
}
