package test;

import com.mysql.jdbc.ResultSet;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class Login extends javax.swing.JFrame {

    private boolean isPasswordVisible = false;

    public Login() {

        initComponents();
        setIconImage();
        getContentPane().setBackground(new java.awt.Color(0, 119, 204));
        initializePasswordField();

        usernameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (usernameTxt.getText().isEmpty()) {
                    usernameTxt.setText("Username");
                }
            }
        });

        passwordTxt1.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (new String(passwordTxt1.getPassword()).isEmpty()) {
                    passwordTxt1.setText("Password");
                    // Reset echo char when placeholder is shown
                    passwordTxt1.setEchoChar((char) 0);
                }
            }
        });
    }

    private void initializePasswordField() {

        passwordTxt1.setText("Password");
        passwordTxt1.setEchoChar((char) 0);

        // Add focus listener to handle placeholder behavior with password masking
        passwordTxt1.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (new String(passwordTxt1.getPassword()).equals("Password")) {
                    passwordTxt1.setText("");
                    // Set echo char based on current visibility state
                    if (!isPasswordVisible) {
                        passwordTxt1.setEchoChar('*');
                    } else {
                        passwordTxt1.setEchoChar((char) 0);
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dentalimg = new javax.swing.JLabel();
        mainLogo = new javax.swing.JLabel();
        brandTxt = new javax.swing.JLabel();
        taglineTxt = new javax.swing.JLabel();
        healthy2 = new javax.swing.JLabel();
        haveAnAccLabel = new javax.swing.JLabel();
        signUpBtn = new javax.swing.JButton();
        usernameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginBtn = new test.CustomButton();
        passwordTxt1 = new javax.swing.JPasswordField();
        hideShwIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PACIFIC KINGS DENTAL CLINIC (LOG IN)");
        setBackground(new java.awt.Color(0, 119, 255));

        dentalimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/leftpanelimg.png"))); // NOI18N

        mainLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/200x200.png"))); // NOI18N
        mainLogo.setMaximumSize(new java.awt.Dimension(360, 200));
        mainLogo.setMinimumSize(new java.awt.Dimension(360, 200));
        mainLogo.setPreferredSize(new java.awt.Dimension(360, 200));

        brandTxt.setFont(new java.awt.Font("Poppins Black", 1, 22)); // NOI18N
        brandTxt.setForeground(new java.awt.Color(255, 255, 255));
        brandTxt.setText("PACIFIC KINGS DENTAL CLINIC");

        taglineTxt.setFont(new java.awt.Font("Poppins Light", 2, 16)); // NOI18N
        taglineTxt.setForeground(new java.awt.Color(255, 255, 255));
        taglineTxt.setText("\"Where Your Healthy Smiles Begin\"");

        healthy2.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        healthy2.setForeground(new java.awt.Color(255, 255, 255));
        healthy2.setText("LOGIN");

        haveAnAccLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        haveAnAccLabel.setForeground(new java.awt.Color(255, 255, 255));
        haveAnAccLabel.setText("Don't have an Account?");

        signUpBtn.setFont(new java.awt.Font("Poppins Medium", 1, 15)); // NOI18N
        signUpBtn.setForeground(new java.awt.Color(255, 255, 255));
        signUpBtn.setText("Sign up");
        signUpBtn.setBorder(null);
        signUpBtn.setBorderPainted(false);
        signUpBtn.setContentAreaFilled(false);
        signUpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signUpBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signUpBtnMouseExited(evt);
            }
        });
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });

        usernameTxt.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        usernameTxt.setForeground(new java.awt.Color(255, 255, 255));
        usernameTxt.setText("Username");
        usernameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        usernameTxt.setOpaque(false);
        usernameTxt.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        usernameTxt.setSelectionColor(new java.awt.Color(153, 255, 153));
        usernameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameTxtMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/userprofiles.png"))); // NOI18N
        jLabel1.setText("  ");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/unlock.png"))); // NOI18N

        loginBtn.setBackground(new java.awt.Color(0, 102, 0));
        loginBtn.setBorder(null);
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Log in");
        loginBtn.setBorderColor(new java.awt.Color(0, 102, 0));
        loginBtn.setColor(new java.awt.Color(0, 102, 0));
        loginBtn.setColorClick(new java.awt.Color(0, 51, 0));
        loginBtn.setColorOver(new java.awt.Color(0, 153, 0));
        loginBtn.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        loginBtn.setRadius(20);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        passwordTxt1.setBackground(new java.awt.Color(0, 119, 204));
        passwordTxt1.setFont(new java.awt.Font("Poppins Light", 0, 16)); // NOI18N
        passwordTxt1.setForeground(new java.awt.Color(255, 255, 255));
        passwordTxt1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        hideShwIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/unhidden.png"))); // NOI18N
        hideShwIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideShwIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dentalimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(mainLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(86, 86, 86))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(brandTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(taglineTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(healthy2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(250, 250, 250))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(haveAnAccLabel)
                                        .addGap(27, 27, 27)
                                        .addComponent(signUpBtn)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(800, 800, 800))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(passwordTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hideShwIcon))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(brandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taglineTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(healthy2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(hideShwIcon))))
                    .addComponent(passwordTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(haveAnAccLabel)
                    .addComponent(signUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(dentalimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        brandTxt.getAccessibleContext().setAccessibleName("HEALTHY");

        setSize(new java.awt.Dimension(816, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        // TODO add your handling code here:
        MouseClick.playClickSound();
        Register signup = new Register();
        signup.setVisible(true);
        dispose();

    }//GEN-LAST:event_signUpBtnActionPerformed

    private void signUpBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpBtnMouseEntered
        // TODO add your handling code here:
        signUpBtn.setForeground(new java.awt.Color(0, 51, 0));
    }//GEN-LAST:event_signUpBtnMouseEntered

    private void signUpBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpBtnMouseExited
        // TODO add your handling code here:
        signUpBtn.setForeground(new java.awt.Color(255, 255, 255));

    }//GEN-LAST:event_signUpBtnMouseExited

    private void usernameTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameTxtMouseClicked
        // TODO add your handling code here:
        if (usernameTxt.getText().equals("Username")) {
            usernameTxt.setText("");
        }

    }//GEN-LAST:event_usernameTxtMouseClicked

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        MouseClick.playClickSound();
        String username = usernameTxt.getText();
        String password = passwordTxt1.getText();

        // Basic validation
        if (username.isEmpty() || username.equals("Username")
                || password.isEmpty() || password.equals("Password")) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);
            MouseClick.playClickSound();
            return;
        }

        try {
            // Get database connection
            Connection conn = DbConnection.connectToDb();
            if (conn == null) {
                JOptionPane.showMessageDialog(null, "Failed to connect to database", "Error", JOptionPane.ERROR_MESSAGE);
                MouseClick.playClickSound();
                return;
            }

            // Prepare SQL statement to check user credentials
            String sql = "SELECT * FROM users WHERE username = ? AND password = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, username);
            pstmt.setString(2, password);

            // Execute query
            ResultSet rs = (ResultSet) pstmt.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Log in Successful");
                // Clear fields after successful login
                usernameTxt.setText("Username");
                passwordTxt1.setText("Password");
                MouseClick.playClickSound();
                // Navigate to LandingPage
                LandingPage land = new LandingPage(username);
                land.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Invalid username or password", "Error", JOptionPane.ERROR_MESSAGE);
                MouseClick.playClickSound();
            }

            // Close resources
            rs.close();
            pstmt.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            MouseClick.playClickSound();
        }


    }//GEN-LAST:event_loginBtnActionPerformed

    private void hideShwIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideShwIconMouseClicked
        // TODO add your handling code here:
        if (!new String(passwordTxt1.getPassword()).equals("Password")) {
            if (isPasswordVisible) {
                // Hide password - show asterisks
                passwordTxt1.setEchoChar('*');
                hideShwIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/unhidden.png")));
                isPasswordVisible = false;
            } else {
                // Show password - display plain text
                passwordTxt1.setEchoChar((char) 0); // 0 means no echo character (plain text)
                hideShwIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hidden.png")));
                isPasswordVisible = true;
            }
        }
    }//GEN-LAST:event_hideShwIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {

            try {
                UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
            Login homePage = new Login();
            homePage.setLocationRelativeTo(null);
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brandTxt;
    private javax.swing.JLabel dentalimg;
    private javax.swing.JLabel haveAnAccLabel;
    private javax.swing.JLabel healthy2;
    private javax.swing.JLabel hideShwIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private test.CustomButton loginBtn;
    private javax.swing.JLabel mainLogo;
    private javax.swing.JPasswordField passwordTxt1;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JLabel taglineTxt;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../icon/32x32LOGO.png")));
    }
}
