package test;

public class TransactionManagement extends javax.swing.JPanel {

    public TransactionManagement() {
        initComponents();
//        createTrnsctn.setVisible(false);
        mngmntDD.setBackground(new java.awt.Color(0, 119, 204));
        mngmntDD.setForeground(new java.awt.Color(255, 255, 255));
        mngmntTbl.getTableHeader().setBackground(new java.awt.Color(0, 119, 204));
        mngmntTbl.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        mngmntTbl.getTableHeader().setFont(new java.awt.Font("Poppins Medium", 0, 14));
        mngmntTbl.getTableHeader().setOpaque(false);
    }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mngmntDD = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        mngmntTbl = new javax.swing.JTable();
        tnsMngmntPanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 119, 204));
        jLabel1.setText("Transaction Management Page");

        mngmntDD.setBackground(new java.awt.Color(0, 119, 204));
        mngmntDD.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        mngmntDD.setForeground(new java.awt.Color(255, 255, 255));
        mngmntDD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Create New Transaction", "View All Transactions", "Find Transaction by ID", "Find Transactions by Patient", "Find Transactions by Date", "Update Transaction", "Delete Transaction" }));

        mngmntTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Patient", "Transaction Type", "Cost", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mngmntTbl);

        tnsMngmntPanel.setBackground(new java.awt.Color(0, 119, 204));
        tnsMngmntPanel.setMaximumSize(new java.awt.Dimension(100, 180));
        tnsMngmntPanel.setMinimumSize(new java.awt.Dimension(100, 180));
        tnsMngmntPanel.setPreferredSize(new java.awt.Dimension(100, 180));

        javax.swing.GroupLayout tnsMngmntPanelLayout = new javax.swing.GroupLayout(tnsMngmntPanel);
        tnsMngmntPanel.setLayout(tnsMngmntPanelLayout);
        tnsMngmntPanelLayout.setHorizontalGroup(
            tnsMngmntPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tnsMngmntPanelLayout.setVerticalGroup(
            tnsMngmntPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(274, 274, 274))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mngmntDD, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(tnsMngmntPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(mngmntDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tnsMngmntPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> mngmntDD;
    private javax.swing.JTable mngmntTbl;
    private javax.swing.JPanel tnsMngmntPanel;
    // End of variables declaration//GEN-END:variables
}
