package test;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class TransactionType extends javax.swing.JPanel {

    public TransactionType() {
        initComponents();
        transDD.setBackground(new java.awt.Color(0, 119, 204));
        transDD.setForeground(new java.awt.Color(255, 255, 255));
        transDD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Add Transaction Type", "View All Transaction Type", "Update Transaction Type", "Find Transaction by ID", "Delete Transaction Type"}));
        transTbl.getTableHeader().setBackground(new java.awt.Color(0, 119, 204));
        transTbl.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        transTbl.getTableHeader().setFont(new java.awt.Font("Poppins Medium", 0, 14));
        transTbl.getTableHeader().setOpaque(false);

        setupCustomScrollbar();
    }

    private void setupCustomScrollbar() {
        // Create custom scrollbars
        scrollpane verticalScrollBar = new scrollpane();
        scrollpane horizontalScrollBar = new scrollpane();

        // Set the custom scrollbars to the JScrollPane
        jScrollPane1.setVerticalScrollBar(verticalScrollBar);
        jScrollPane1.setHorizontalScrollBar(horizontalScrollBar);

        // Optional: Configure scrollbar policies
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        // Optional: Set scrollbar colors to match your theme
        verticalScrollBar.setForeground(new java.awt.Color(0, 119, 204));
        horizontalScrollBar.setForeground(new java.awt.Color(0, 119, 204));
    }

    public void viewAllTransactionType() {
        try {
            Connection conn = DbConnection.connectToDb();
            if (conn != null) {
                // Query to get transaction type data - adjust column names based on your database schema
                String query = "SELECT TypeID, TypeName, DefaultCost FROM transactiontype";
                PreparedStatement pst = conn.prepareStatement(query);
                ResultSet rs = pst.executeQuery();

                // Get the table model
                DefaultTableModel model = (DefaultTableModel) transTbl.getModel();

                // Clear existing rows
                model.setRowCount(0);

                // Add data from database to table
                while (rs.next()) {
                    Object[] row = {
                        rs.getInt("TypeID"),
                        rs.getString("TypeName"),
                        rs.getString("DefaultCost")
                    };
                    model.addRow(row);
                }

                // Close resources
                rs.close();
                pst.close();
                conn.close();

            } else {
                JOptionPane.showMessageDialog(this, "Failed to connect to database", "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            System.err.println("Database error: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Error retrieving transaction type data: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            System.err.println("Unexpected error: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jLabel1 = new javax.swing.JLabel();
        transDD = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        transTbl = new javax.swing.JTable();
        transTypePanel = new javax.swing.JPanel();

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 119, 204));
        jLabel1.setText("Transaction Type Page");

        transDD.setBackground(new java.awt.Color(0, 119, 204));
        transDD.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        transDD.setForeground(new java.awt.Color(255, 255, 255));
        transDD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Add New Transaction Type", " View All Transaction Types", " Find Transaction Type by ID", " Update Transaction Type", " Delete Transaction Type" }));
        transDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transDDActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        transTbl.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        transTbl.setForeground(new java.awt.Color(0, 119, 204));
        transTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Names", "Default Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        transTbl.setGridColor(new java.awt.Color(255, 255, 255));
        transTbl.setRowHeight(25);
        transTbl.setSelectionBackground(new java.awt.Color(0, 119, 204));
        transTbl.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(transTbl);

        transTypePanel.setBackground(new java.awt.Color(0, 119, 204));
        transTypePanel.setMaximumSize(new java.awt.Dimension(100, 180));
        transTypePanel.setMinimumSize(new java.awt.Dimension(100, 180));
        transTypePanel.setPreferredSize(new java.awt.Dimension(100, 180));

        javax.swing.GroupLayout transTypePanelLayout = new javax.swing.GroupLayout(transTypePanel);
        transTypePanel.setLayout(transTypePanelLayout);
        transTypePanelLayout.setHorizontalGroup(
            transTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        transTypePanelLayout.setVerticalGroup(
            transTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(transDD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(307, 307, 307))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(transTypePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(transDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transTypePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void transDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transDDActionPerformed
        // TODO add your handling code here:
        MouseClick.playClickSound();
        String selectedOption = (String) transDD.getSelectedItem();
        transTypePanel.removeAll();

        if (null != selectedOption) {
            switch (selectedOption) {
                case "Add Transaction Type" -> {
                    //            MouseClick.playClickSound();
                    AddNewTransaction addTransPanel = new AddNewTransaction();
                    addTransPanel.setSize(transTypePanel.getSize());
                    transTypePanel.add(addTransPanel);
                }
                case "View All Transaction Type" -> {
                    viewAllTransactionType();
                    // Clear patientPanel as the table is displayed above
                    transTypePanel.removeAll();
                }
                case "Update Transaction Type" -> {
                    UpdateTransactionType updatePanel = new UpdateTransactionType();
                    updatePanel.setSize(transTypePanel.getSize());
                    transTypePanel.add(updatePanel);
                }
                case "Find Transaction by ID" -> {
                    FindTransactionByID findByIDPanel = new FindTransactionByID();
                    findByIDPanel.setSize(transTypePanel.getSize());
                    transTypePanel.add(findByIDPanel);
                }
                case "Delete Transaction Type" -> {
                    DeleteTransactionType deletePanel = new DeleteTransactionType();
                    deletePanel.setSize(transTypePanel.getSize());
                    transTypePanel.add(deletePanel);
                }
                default -> {
                }
            }
        }
        transTypePanel.revalidate();
        transTypePanel.repaint();


    }//GEN-LAST:event_transDDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private javax.swing.JComboBox<String> transDD;
    private javax.swing.JTable transTbl;
    private javax.swing.JPanel transTypePanel;
    // End of variables declaration//GEN-END:variables
}
