/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test;

import java.awt.event.ActionListener;

/**
 *
 * @author Admin
 */
public class updatePatientModal extends javax.swing.JPanel {

    /**
     * Creates new form updatePatientModal
     */
    public updatePatientModal() {
        initComponents();
    }
    public void setPatientData(String firstName, String middleName, String lastName, String age, String address,
                               String birthdate, String contactNumber, String email) {
        jTextField1.setText(firstName);
        jTextField2.setText(middleName);
        jTextField3.setText(lastName);
        jTextField4.setText(age);
        jTextField5.setText(address);
        jTextField6.setText(birthdate);
        jTextField7.setText(contactNumber);
        jTextField9.setText(email);
    }

    public String getFirstName() {
        return jTextField1.getText();
    }

    public String getMiddleName() {
        return jTextField2.getText();
    }

    public String getLastName() {
        return jTextField3.getText();
    }

    public String getAge() {
        return jTextField4.getText();
    }

    public String getAddress() {
        return jTextField5.getText();
    }

    public String getBirthdate() {
        return jTextField6.getText();
    }

    public String getContactNumber() {
        return jTextField7.getText();
    }

    public String getEmail() {
        return jTextField9.getText();
    }

    public void setSaveAction(Runnable saveAction) {
        for (ActionListener al : customButton1.getActionListeners()) {
            customButton1.removeActionListener(al);
        }
        customButton1.addActionListener(evt -> saveAction.run());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        name7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        name5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        name6 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        name8 = new javax.swing.JLabel();
        customButton1 = new test.CustomButton();

        jTextField8.setBackground(new java.awt.Color(0, 119, 204));
        jTextField8.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setText("current number");
        jTextField8.setBorder(null);

        name7.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        name7.setForeground(new java.awt.Color(255, 255, 255));
        name7.setText("Contact number:");

        setBackground(new java.awt.Color(0, 119, 204));
        setMaximumSize(new java.awt.Dimension(448, 168));
        setMinimumSize(new java.awt.Dimension(448, 168));
        setPreferredSize(new java.awt.Dimension(448, 168));

        jLabel1.setBackground(new java.awt.Color(0, 119, 204));
        jLabel1.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update  Patient  details");

        name.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Name: ");

        name1.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setText("Midlename:");

        name2.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        name2.setForeground(new java.awt.Color(255, 255, 255));
        name2.setText("Lastname:");

        name3.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        name3.setForeground(new java.awt.Color(255, 255, 255));
        name3.setText("Age:");

        name4.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        name4.setForeground(new java.awt.Color(255, 255, 255));
        name4.setText("Adress:");

        name5.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        name5.setForeground(new java.awt.Color(255, 255, 255));
        name5.setText("Birthdate (yyyy-MM-dd):");

        jTextField1.setBackground(new java.awt.Color(0, 119, 204));
        jTextField1.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("current name");
        jTextField1.setBorder(null);

        jTextField2.setBackground(new java.awt.Color(0, 119, 204));
        jTextField2.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("current MN");
        jTextField2.setBorder(null);

        jTextField3.setBackground(new java.awt.Color(0, 119, 204));
        jTextField3.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("current LN");
        jTextField3.setBorder(null);

        jTextField4.setBackground(new java.awt.Color(0, 119, 204));
        jTextField4.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("current Age");
        jTextField4.setBorder(null);

        jTextField5.setBackground(new java.awt.Color(0, 119, 204));
        jTextField5.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("current Adress");
        jTextField5.setBorder(null);

        jTextField6.setBackground(new java.awt.Color(0, 119, 204));
        jTextField6.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setText("current BD");
        jTextField6.setBorder(null);

        jTextField7.setBackground(new java.awt.Color(0, 119, 204));
        jTextField7.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setText("current number");
        jTextField7.setBorder(null);

        name6.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        name6.setForeground(new java.awt.Color(255, 255, 255));
        name6.setText("Contact number:");

        jTextField9.setBackground(new java.awt.Color(0, 119, 204));
        jTextField9.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setText("current email");
        jTextField9.setBorder(null);

        name8.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        name8.setForeground(new java.awt.Color(255, 255, 255));
        name8.setText("Email:");

        customButton1.setBackground(new java.awt.Color(0, 51, 0));
        customButton1.setForeground(new java.awt.Color(255, 255, 255));
        customButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/updateBtn.png"))); // NOI18N
        customButton1.setText("Save Changes");
        customButton1.setBorderColor(new java.awt.Color(0, 51, 0));
        customButton1.setColor(new java.awt.Color(0, 51, 0));
        customButton1.setColorClick(new java.awt.Color(0, 51, 0));
        customButton1.setColorOver(new java.awt.Color(0, 51, 0));
        customButton1.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        customButton1.setRadius(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(name2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(name3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(name)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(name1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(name8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(name6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField7)))))
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(name5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(name4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(customButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name8)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(name6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name2)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name3)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name4)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name5)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(customButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private test.CustomButton customButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JLabel name6;
    private javax.swing.JLabel name7;
    private javax.swing.JLabel name8;
    // End of variables declaration//GEN-END:variables
}
