/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test;

import javax.swing.JOptionPane;

public class UpdateTransactionType extends javax.swing.JPanel implements TransactionTypeServiceAware {

    private String currentTransType = "";
    private String currentDesc = "";
    private String currentCost = "";
    private int currentTypeID = -1;
    private UpdateTransactionModal updateModal = null;
    private TransactionTypeService transactionTypeService; // Service injected via interface

    // Modified constructor
    public UpdateTransactionType() {
        initComponents();
        resultModal.setVisible(false);
        editBtn.setVisible(false);
    }

    @Override
    public void setTransactionTypeService(TransactionTypeService transactionTypeService) {
        this.transactionTypeService = transactionTypeService;
    }

    public void viewAllTransactionType() {
        if (getParent() instanceof TransactionTypePage) {
            ((TransactionTypePage) getParent()).viewAllTransactionType();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        updateID = new javax.swing.JTextField();
        resultModal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        transType = new javax.swing.JLabel();
        descType = new javax.swing.JLabel();
        costType = new javax.swing.JLabel();
        editBtn = new test.CustomButton();
        searchID = new test.CustomButton();

        setBackground(new java.awt.Color(0, 119, 204));
        setMaximumSize(new java.awt.Dimension(452, 180));
        setMinimumSize(new java.awt.Dimension(452, 180));
        setPreferredSize(new java.awt.Dimension(452, 180));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Transaction Type");

        jLabel2.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Transaction Type ID to Update:");

        updateID.setBackground(new java.awt.Color(0, 119, 204));
        updateID.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        updateID.setForeground(new java.awt.Color(255, 255, 255));
        updateID.setBorder(null);

        resultModal.setBackground(new java.awt.Color(0, 119, 204));
        resultModal.setMinimumSize(new java.awt.Dimension(327, 100));

        jLabel3.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Current Transaction Type Details:");

        jLabel4.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Transaction Type:");

        jLabel5.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Description:");

        jLabel6.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Default Cost:");

        transType.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        transType.setForeground(new java.awt.Color(255, 255, 255));
        transType.setText("None");

        descType.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        descType.setForeground(new java.awt.Color(255, 255, 255));
        descType.setText("None");

        costType.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        costType.setForeground(new java.awt.Color(255, 255, 255));
        costType.setText("None");

        javax.swing.GroupLayout resultModalLayout = new javax.swing.GroupLayout(resultModal);
        resultModal.setLayout(resultModalLayout);
        resultModalLayout.setHorizontalGroup(
            resultModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultModalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(resultModalLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transType, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(resultModalLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(resultModalLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(costType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        resultModalLayout.setVerticalGroup(
            resultModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultModalLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resultModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(transType, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resultModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(descType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(resultModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(costType))
                .addContainerGap())
        );

        editBtn.setBackground(new java.awt.Color(0, 51, 0));
        editBtn.setBorder(null);
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        editBtn.setText("Edit Details");
        editBtn.setBorderColor(new java.awt.Color(0, 51, 0));
        editBtn.setColor(new java.awt.Color(0, 51, 0));
        editBtn.setColorClick(new java.awt.Color(2, 22, 2));
        editBtn.setColorOver(new java.awt.Color(0, 102, 0));
        editBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        editBtn.setRadius(10);
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        searchID.setBackground(new java.awt.Color(0, 51, 0));
        searchID.setForeground(new java.awt.Color(255, 255, 255));
        searchID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/searchBtn.png"))); // NOI18N
        searchID.setText("Search ID");
        searchID.setBorderColor(new java.awt.Color(0, 51, 0));
        searchID.setColor(new java.awt.Color(0, 51, 0));
        searchID.setColorClick(new java.awt.Color(4, 29, 2));
        searchID.setColorOver(new java.awt.Color(0, 102, 0));
        searchID.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        searchID.setRadius(12);
        searchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(resultModal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateID, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(updateID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchID, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultModal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchIDActionPerformed
        // TODO add your handling code here
        MouseClick.playClickSound();
        String inputID = updateID.getText().trim();

        // Validate input
        if (inputID.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a Transaction Type ID to search.",
                    "Input Required",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validate if input is a number
        int typeID;
        try {
            typeID = Integer.parseInt(inputID);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a valid numeric Transaction Type ID.",
                    "Invalid Input",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Use service to fetch transaction type
            TransactionType type = transactionTypeService.getTransactionType(typeID);

            if (type != null) {
                // Transaction type found - populate the result modal
                currentTypeID = type.getTypeID();
                currentTransType = type.getTypeName() != null ? type.getTypeName() : "";
                currentDesc = type.getDescription() != null ? type.getDescription() : "";
                currentCost = type.getDefaultCost() != 0 ? String.valueOf(type.getDefaultCost()) : "";

                // Set the labels with retrieved data
                transType.setText(currentTransType.isEmpty() ? "None" : currentTransType);
                descType.setText(currentDesc.isEmpty() ? "None" : currentDesc);
                costType.setText(currentCost.isEmpty() ? "None" : currentCost);

                // Show the result modal and edit button
                resultModal.setVisible(true);
                editBtn.setVisible(true);

                // Refresh the panel
                this.revalidate();
                this.repaint();
            } else {
                // No transaction type found
                JOptionPane.showMessageDialog(this,
                        "No Transaction Type found with ID: " + typeID,
                        "Not Found",
                        JOptionPane.INFORMATION_MESSAGE);

                // Hide the result modal and edit button
                resultModal.setVisible(false);
                editBtn.setVisible(false);

                // Refresh the panel
                this.revalidate();
                this.repaint();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error retrieving transaction type: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            resultModal.setVisible(false);
            editBtn.setVisible(false);
        }
    }//GEN-LAST:event_searchIDActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        MouseClick.playClickSound();

        // Hide the result modal
        resultModal.setVisible(false);

        // Create the update modal panel with current data
        updateModal = new UpdateTransactionModal();
        updateModal.setTransactionTypeService(transactionTypeService); // Pass the service

        // Set the current values in the update modal text fields
        updateModal.setTransactionData(currentTransType, currentDesc, currentCost, currentTypeID);

        // Add the update modal to the same location as resultModal
        java.awt.Rectangle bounds = resultModal.getBounds();
        updateModal.setBounds(bounds);

        // Add to the parent container
        this.add(updateModal);
        updateModal.setVisible(true);

        // Hide the edit button
        editBtn.setVisible(false);

        // Refresh the panel
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_editBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel costType;
    private javax.swing.JLabel descType;
    private test.CustomButton editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel resultModal;
    private test.CustomButton searchID;
    private javax.swing.JLabel transType;
    private javax.swing.JTextField updateID;
    // End of variables declaration//GEN-END:variables
}
